# NumPy biblioteka

<br>

---

NumPy (Numerical Python) yra Python programavimo kalbos biblioteka, skirta efektyviam skaičiavimui su dideliais duomenų kiekiais. NumPy suteikia aukšto lygio matematikos funkcijas ir leidžia dirbti su daugiamatėmis masyvais bei matricomis. Ši biblioteka yra plačiai naudojama mokslo, inžinerijos, duomenų analizės ir dirbtinio intelekto srityse.<br>

NumPy pagrindu sukurtos beveik visos su duomenų mokslu susijusios bibliotekos, tokios kaip Pandas ir kt. Numpy procedūriškai yra itin greita, nes yra susieta ryšiais (`bindings`) su C kalba parašytais moduliais.

<br>

Pagrindinės NumPy funkcijos ir savybės:

1. <b>Daugiamačiai masyvai:</b> NumPy teikia masyvų objektą, vadinamą `numpy.ndarray`, kuris yra efektyvus daugiamačių duomenų laikymui ir operacijoms su jais.

2. <b>Universaliųjų funkcijų (ufunc):</b> NumPy palaiko efektyvų elementarių operacijų vykdymą su masyvais, įskaitant sudėties, atimties, daugybos, dalybos ir kitas operacijas.

3. <b>Transponavimas ir indeksavimas:</b> NumPy leidžia lengvai transponuoti masyvus ir vykdyti įvairius indeksavimo metodus, leidžiančius greitai pasiekti ir manipuliuoti duomenimis.

4. <b>Matricų operacijos:</b> NumPy suteikia įvairias matricų operacijas, įskaitant matricų sudauginimą, inversiją ir kitas.

5. <b>Atsitiktiniai skaičiai:</b> NumPy turi modulį numpy.random, kuris leidžia generuoti atsitiktinius skaičius ir masyvus.

NumPy yra pagrindinė daugelio kitų populiarių Python mokslinių ir inžinerinių bibliotekų pagrindas, įskaitant `Pandas`, `SciPy`, `Matplotlib` ir kitas. Tai puikus įrankis dirbant su duomenimis, atliekant skaičiavimus ir vykdant mokslinius tyrimus Python aplinkoje.

* Standartiškai įsidiegia `*pip install numpy*`, jeigu naudojate Anaconda - `*conda install numpy*`

* Papildomai rekomenduojama suinstaliuioti `seaborn`:

`pip install seaborn`

`Seaborn` suinstaliuoja visus reikiamus komponentus, kurie bus reikalingi ateityje, besimokant kurso medžiagą (`pandas`, `pillow`, `matplotlib` ir pan.).

* Dažniausiai naudojamas NumPy ingredientas - NumPy masyvai, arba kitaip dar gali būti vadinami `kitokie sąrašai` (`numpy array`). Jie būna dviejų tipų - vektoriai ir matricos.

Prieš pradedant darbą su NumPy, reikia jį importuoti.

In [138]:
import numpy as np

Tarkime, turime paprastą Python list'ą:

In [139]:
listas = [1, 2, 3, 4, 5]

Paverskime jį į NumPy array:

In [140]:
arr = np.array(listas)

In [141]:
arr

array([1, 2, 3, 4, 5])

Gauname 1 lygio NumPy masyvą (vektorių). Jeigu norime matricos, turime sukurti keletą masyvų masyve:

In [142]:
mano_listai = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
matrica = np.array(mano_listai)


In [143]:
matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Masyvas gali būti tiek vektorius, tiek ir matrica.<br>
Dar vienas pavyzdys:

In [144]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Darom matricą:

In [145]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


NumPy trumpinys `np` pripažintas visame pasaulyje ir yra naudotinas.

In [146]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


NumPy turi ir integruotus, paprastus būdus susikurti masyvą. Skliausteliuose reikia įrašyti start, stop ir step(nebūtina) reikšmes:

In [147]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Naudojant `NumPy` biblioteką ir jos funkciją `arange` sukuriamas masyvas, kuris prasideda nuo 5 ir baigiasi prieš 202, su žingsniu 5. Tai reiškia, kad masyvas bus sukurtas su visais skaičiais nuo 5 iki 202 (neįskaitant), kurie yra padalinti iš 5 be liekanos:

In [148]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


Jeigu reikia vektoriaus iš nulių:

In [149]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

`np.zeros` gražina sąrašą `array` užpildytą nuliais, kiek nulių paprašysime, tiek nulių duos:

In [150]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


Jeigu reikia matricos iš nulių:

In [151]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Dar vienas pavyzdys,kurio metu argumentą `np.zeros` galime paprašyti, kad gražintų matricą.<br>
Argumentą nusirodome kaip `tuple`:

In [152]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Analogiškai veikia `np.ones` metodas:

In [153]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Dar viena naudinga funkcija - `linspace`.<br>
Ji grąžina masyvą, su lygiais intervalais išdėliotomis reikšmėmis. Reikia nurodyti start, stop ir intervalo reikšmes:

In [154]:
np.linspace(1, 11, 3)

array([ 1.,  6., 11.])

In [155]:
np.linspace(1, 11, 5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [156]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [157]:
np.linspace(0,20,16)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ,
       13.33333333, 14.66666667, 16.        , 17.33333333, 18.66666667,
       20.        ])

Jeigu prireikė vienetinės matricos, siekiant sulyginti vieną sąrašą su kitu, naudojam `np.eye` matricą:

In [158]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [159]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<br>

# Random arrays kūrimas

Pirmas metodas susikurti random array - `np.random.rand()`.<br>
Jo pagalba galime susikurti masyvą su atsitiktinėm reikšmėm nuo 0 iki 1 `("uniform" distribution)`

In [160]:
np.random.rand(5)

array([0.53389382, 0.58354474, 0.08424411, 0.90104474, 0.12178817])

In [161]:
np.random.rand(10)

array([0.11592165, 0.80209762, 0.82984609, 0.38043961, 0.14199502,
       0.77210869, 0.35441812, 0.26783703, 0.18614496, 0.42603273])

jeigu norime ne vektoriaus, o matricos:

In [162]:
np.random.rand(5, 5)

array([[0.51810507, 0.86053374, 0.88080961, 0.6788275 , 0.82544676],
       [0.16814126, 0.94779414, 0.6100183 , 0.87759897, 0.59653546],
       [0.99946198, 0.22235855, 0.97088562, 0.99331981, 0.98417269],
       [0.83227671, 0.51797487, 0.60915862, 0.34604483, 0.61115637],
       [0.4389802 , 0.49885196, 0.37470492, 0.46716469, 0.75658992]])

`np.random.randn()` sugeneruos reikšmes iš  `“standard normal” distribution` (standartinis normalusis skirstinys)

In [163]:
np.random.randn(3, 3)

array([[-1.07225603, -2.11647598,  0.3386388 ],
       [ 1.3093338 , -1.21334886,  0.45944713],
       [ 1.71844017, -1.26432266,  0.11014165]])

`randn` leidžia ir neigiamas reikšmes:

In [164]:
np.random.randn(4, 4)

array([[-0.59264421,  0.70242781, -1.82389969,  0.58637058],
       [-1.58209647, -0.3318741 ,  1.58764484, -0.61417899],
       [-0.48607957,  0.78264842,  1.09425804,  0.75386647],
       [ 1.95014031,  0.84015634, -0.13023738, -0.54675418]])

`np.random.randint()` sugeneruoja atsitiktines integer reikšmes. Parametruose reikia nurodyti, žemiausią, aukščiausią (neįskaitant) reikšmes ir norimą kiekį reikšmių.

In [165]:
np.random.randint(100, 200, 20)

array([166, 140, 178, 191, 192, 107, 175, 166, 109, 194, 159, 122, 116,
       178, 107, 128, 198, 165, 139, 153])

In [166]:
np.random.randint(1, 100, (5, 5))

array([[10, 54,  8,  1,  4],
       [43, 45, 41, 66, 78],
       [22, 85, 59, 17, 27],
       [95, 86, 66,  6, 12],
       [83, 17, 34,  7, 87]])

<br>

# Masyvų pertvarkymas

`reshape()` metodas leidžia mums performuoti turimą masyvą į kitą formą:

In [167]:
my_array = np.random.randint(0, 100, 64)

In [168]:
my_array

array([35, 97,  6, 24, 67, 68, 14, 28, 74, 40, 52, 23,  4, 78, 61, 87, 66,
        3, 61, 56, 43, 32, 48, 49, 46, 93, 37, 48, 36, 48,  3, 30, 73, 85,
       89,  0, 40, 65, 68, 13,  5, 81,  8, 12, 92, 37, 18, 98, 71,  7, 36,
       86, 79, 30, 38, 82, 36, 50, 65, 27, 56, 26,  3, 52])

In [169]:
betko64 = np.random.randint(10, 100, 64)
betko64

array([54, 51, 83, 47, 42, 47, 58, 64, 82, 55, 35, 73, 88, 67, 36, 91, 92,
       25, 60, 59, 91, 94, 19, 34, 71, 47, 58, 69, 35, 42, 51, 45, 20, 26,
       44, 96, 76, 24, 19, 85, 65, 21, 89, 76, 22, 97, 63, 87, 34, 14, 52,
       63, 69, 48, 89, 95, 98, 76, 33, 45, 86, 30, 66, 71])

šiame pavyzdyje vektorių iš 64 reikšmių performavome į 8x8 matricą:

In [170]:
betko8x8 = betko64.reshape(8, 8)
betko8x8

array([[54, 51, 83, 47, 42, 47, 58, 64],
       [82, 55, 35, 73, 88, 67, 36, 91],
       [92, 25, 60, 59, 91, 94, 19, 34],
       [71, 47, 58, 69, 35, 42, 51, 45],
       [20, 26, 44, 96, 76, 24, 19, 85],
       [65, 21, 89, 76, 22, 97, 63, 87],
       [34, 14, 52, 63, 69, 48, 89, 95],
       [98, 76, 33, 45, 86, 30, 66, 71]])

In [171]:
reshaped_array = my_array.reshape(8, 8)

In [172]:
reshaped_array

array([[35, 97,  6, 24, 67, 68, 14, 28],
       [74, 40, 52, 23,  4, 78, 61, 87],
       [66,  3, 61, 56, 43, 32, 48, 49],
       [46, 93, 37, 48, 36, 48,  3, 30],
       [73, 85, 89,  0, 40, 65, 68, 13],
       [ 5, 81,  8, 12, 92, 37, 18, 98],
       [71,  7, 36, 86, 79, 30, 38, 82],
       [36, 50, 65, 27, 56, 26,  3, 52]])

In [173]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([31, 17, 96, 88, 21, 19, 31, 45, 49, 50, 39, 12, 23, 48, 73, 24, 33,
       13, 41, 84, 28, 18, 50, 34, 77, 73, 87, 21, 70, 16, 87, 59, 49, 20,
       44, 83, 93, 29, 41, 50, 11, 98, 78, 63, 17, 11, 35, 11, 29, 40, 10,
       40, 73, 87, 38, 76])

In [174]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[31, 17, 96, 88, 21, 19, 31],
       [45, 49, 50, 39, 12, 23, 48],
       [73, 24, 33, 13, 41, 84, 28],
       [18, 50, 34, 77, 73, 87, 21],
       [70, 16, 87, 59, 49, 20, 44],
       [83, 93, 29, 41, 50, 11, 98],
       [78, 63, 17, 11, 35, 11, 29],
       [40, 10, 40, 73, 87, 38, 76]])

Taip yra ir transponavimo funkcija:

In [175]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[31, 45, 73, 18, 70, 83, 78, 40],
       [17, 49, 24, 50, 16, 93, 63, 10],
       [96, 50, 33, 34, 87, 29, 17, 40],
       [88, 39, 13, 77, 59, 41, 11, 73],
       [21, 12, 41, 73, 49, 50, 35, 87],
       [19, 23, 84, 87, 20, 11, 11, 38],
       [31, 48, 28, 21, 44, 98, 29, 76]])

Gražiname atgal perrūšiuotą (gražiname į matricą ir gavome sveiką skaičių):

In [176]:
betko7x8.reshape(56)

array([31, 45, 73, 18, 70, 83, 78, 40, 17, 49, 24, 50, 16, 93, 63, 10, 96,
       50, 33, 34, 87, 29, 17, 40, 88, 39, 13, 77, 59, 41, 11, 73, 21, 12,
       41, 73, 49, 50, 35, 87, 19, 23, 84, 87, 20, 11, 11, 38, 31, 48, 28,
       21, 44, 98, 29, 76])

<br>

# Naudingi Metodai

In [177]:
daug_betko = np.random.randn(10, 10)
daug_betko

array([[ 0.94552274, -0.5500494 ,  1.04250208, -0.85379737,  0.98647932,
        -0.05048519,  0.44753463, -1.37123742,  0.88974756,  1.73959935],
       [-0.44258343, -0.8125408 , -0.18154109, -0.78723336, -0.65219737,
        -1.97159909,  0.89933964,  0.24425798,  0.9393124 , -1.21492238],
       [ 0.87667433,  0.17096547,  0.3064958 ,  0.55402641, -0.75280681,
        -0.39466685, -1.31232511,  0.75588654,  0.98670294, -0.1900108 ],
       [ 0.86026579,  0.90205428, -0.2262586 , -0.17609827,  1.0199105 ,
         1.85402038, -0.60729249, -0.02353899, -1.70931117, -1.04997061],
       [-1.03012265, -0.06153668, -1.4042323 , -0.29646245, -2.07084264,
         0.21334514, -0.95610944,  0.46823504, -1.29026951, -0.80689909],
       [ 0.80555423, -0.08988165, -0.47172856,  0.22849292,  0.25516396,
        -0.14517796, -0.2808234 ,  0.99239279, -0.87562784,  1.18435868],
       [-0.88860421,  0.92291386, -2.70834981,  1.36148659,  0.09078991,
         1.34857034, -0.01632305,  1.25673323

`max()` ir `.min()` metodai ištraukia maksimalią ir minimalią reikšmes iš masyvo:

In [178]:
my_array.min()

0

In [179]:
my_array.max()

98

In [180]:
print(daug_betko.shape, daug_betko.dtype)

(10, 10) float64


In [181]:
daug_betko = np.random.randn(10, 10)
print(daug_betko.min(), daug_betko.max())

-2.1991597930739566 2.9478075640118293


In [182]:
daug_betko = np.random.randn(10000, 10000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

75325829:-5.688043718009704, 87302966:5.851125272953631


PASTABA:<br>
didinant skaičius virš 10000 gali išmesti klaidą, nes Jūsų kompiuteris neturės tiek resursų kodui apskaičiuoti!

In [183]:
daug_betko.shape

(10000, 10000)

## Indeksacija ir reikšmių traukimas

In [184]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[9 4 6 7 3 4 2 3 4 8]
9 7 [4 2 3 4]


Atbuline tvarka atrodytų taip:

In [185]:
print(betko10[::-1])

[8 4 3 2 4 3 7 6 4 9]


Sąrašą galima karpyti:

In [186]:
print(betko10[-3:5:-1])

[3 2]


Galima pakeisti skaičius, priskiriant reikšmes, pvz.: kas antrą skaičių paversti nuliu:

In [187]:
betko10[::2] = 0
print(betko10)

[0 4 0 7 0 4 0 3 0 8]


Panašiai vyksta ir su matricomis, skirtumas tik tai, kad per kablelius turime nurodyti koordinates (pvz.: iš betko7x8, x koordinatėje pasiimame viksą, o y - iki 7):

In [188]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[31 45 73 18 70 83 78]
 [17 49 24 50 16 93 63]
 [96 50 33 34 87 29 17]
 [88 39 13 77 59 41 11]
 [21 12 41 73 49 50 35]
 [19 23 84 87 20 11 11]
 [31 48 28 21 44 98 29]] (7, 7) 77


Galima išsipjauti vidurinius rėžius:

In [189]:
print(betko7x7[2:5, 2:5])

[[33 34 87]
 [13 77 59]
 [41 73 49]]


`argmax()` ir `argmin()` nurodo mums maksimalios ir minimalios reikšmių indeksą:

In [190]:
my_array.argmax()

47

In [191]:
my_array.argmin()

35

**.shape** nurodo, kokią formą turi mūsų masyvas:

In [192]:
reshaped_array.shape

(8, 8)

**.dtype** nurodo, koks duomenų tipas yra mūsų masyve:

In [193]:
reshaped_array.dtype

dtype('int32')

In [194]:
sample_array = np.arange(1,10)

In [195]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

reikšmę iš vektoriaus traukiame taip pat kaip ir iš Python sąrašo:

In [196]:
sample_array[5]

6

galime naudoti *slices*:

In [197]:
sample_array[2:8]

array([3, 4, 5, 6, 7, 8])

In [198]:
sample_array[6:]

array([7, 8, 9])

In [199]:
sample_array[-5:]

array([5, 6, 7, 8, 9])

galime pasirinktam rėžiui suteikti kokią nors savo reikšmę *(Broadcasting)*: 

In [200]:
sample_array[4:8] = 50

In [201]:
sample_array

array([ 1,  2,  3,  4, 50, 50, 50, 50,  9])

# Reikšmių traukimas iš matricos 

In [202]:
sample = np.random.randint(1, 10, 25)

In [203]:
sample_matrix = sample.reshape(5,5)

In [204]:
sample_matrix

array([[9, 3, 5, 9, 6],
       [1, 3, 8, 5, 3],
       [7, 4, 1, 8, 7],
       [5, 3, 4, 8, 1],
       [8, 7, 1, 2, 1]])

In [205]:
sample_matrix[2,2] 

1

laužtiniuose skliausteliuose pirmiau nurodome eilutę, paskui tos eilutės nario indeksą.

taip pat galime naudoti rėžius:

In [206]:
sample_matrix[1:4, 1:4]

array([[3, 8, 5],
       [4, 1, 8],
       [3, 4, 8]])

In [207]:
sample_matrix[3:,:]

array([[5, 3, 4, 8, 1],
       [8, 7, 1, 2, 1]])

In [208]:
sample_matrix[:, 0:2]

array([[9, 3],
       [1, 3],
       [7, 4],
       [5, 3],
       [8, 7]])

# Reikšmių traukimas pagal sąlygą

Tarkime, turime masyvą:

In [209]:
masyvas = np.arange(1,21)

In [210]:
masyvas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

norime reikšmių, didesnių už 9:

In [211]:
bool_masyvas = masyvas > 9

In [212]:
bool_masyvas

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

gauname masyvą iš *bool* reikšmių, kuriame True reikšmės atitinka užduotą sąlygą. Atlikime tokią operaciją:

In [213]:
masyvas[bool_masyvas]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

kintamojo *masvas* laužtiniuose skliautuose įvedę kintamąjį *bool_masyvas*, gauname reikšmes, kurios atitinka True indeksą. Tą patį rezultatą galime gauti laužtiniuose skliaustuose tiesiog įrašę sąlygą:

In [214]:
masyvas[masyvas>9]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Numpy elgsenos ypatumai

Yra tam tikri NumPy elgsenos ypatumai, tarkime:

In [215]:
pvz = np.random.randint(1, 21, 20)

In [216]:
pvz

array([12, 11,  5, 20, 13,  9, 20,  5, 12,  2,  9, 10,  6,  2, 12, 20,  7,
        2, 16,  1])

turime *random* masyvą iš integer reikšmių. Susikurkime jo atraižą:

In [217]:
pvz_ispjova = pvz[5:15]

In [218]:
pvz_ispjova

array([ 9, 20,  5, 12,  2,  9, 10,  6,  2, 12])

In [219]:
pvz_ispjova[:] = 99

In [220]:
pvz_ispjova

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

Iki šio momento viskas atrodo kaip ir tikėtąsi. Tačiau išsikvietę pirmąjį masyvą matome:

In [221]:
pvz

array([12, 11,  5, 20, 13, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 20,  7,
        2, 16,  1])

Paprastai kuriant kintamąjį, užkulisiuose padaroma kopija šaltinio, iš kurio jis gaminamas (šiuo atveju *pvz*). 
Iš tos kopijos formuojamas naujas kintamasis. Tačiau NumPy atveju pakeitimai vykdomi originale, ir mums 
rodoma tik modifikuota to originalo dalis. NumPy pritaikytas darbui su milžiniškais kiekiais duomenų. Daryti laikinas jų kopijas atmintyje yra neefektyvu, ir nestabilu. Todėl, kai norime išsaugoti originalą, turime nurodyti, kad norėsime pasidaryti kopiją:

In [222]:
pvz_copy = pvz.copy()

In [223]:
pvz_copy

array([12, 11,  5, 20, 13, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 20,  7,
        2, 16,  1])

In [224]:
pvz_copy == pvz

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [225]:
pvz_copy_ispjova = pvz_copy[5:15]
pvz_copy_ispjova[:] = 100

In [226]:
pvz_copy_ispjova

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [227]:
pvz

array([12, 11,  5, 20, 13, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 20,  7,
        2, 16,  1])

In [228]:
pvz_copy

array([ 12,  11,   5,  20,  13, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100,  20,   7,   2,  16,   1])

Taigi, pasidarėme kopiją, nurodėme kad norime jos rėžio [5:15] kintamąjame *pvz_copy_ispjova*, joje visas reikšmes pakeitėme į 100, ir įsitikinome, kad po to originalusis *pvz* liko nepakeistas.

<br>

## Dar vienas pavyzdys:

In [229]:
senukai = betko7x7 >= 50
print(senukai)

[[False False  True False  True  True  True]
 [False False False  True False  True  True]
 [ True  True False False  True False False]
 [ True False False  True  True False False]
 [False False False  True False  True False]
 [False False  True  True False False False]
 [False False False False False  True False]]


In [230]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[73 70 83 78 50 93 63 96 50 87 88 77 59 73 50 84 87 98] (18,)


In [231]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([31, 45, 18, 17, 49, 24, 16, 33, 34, 29, 17, 39, 13, 41, 11, 21, 12,
        41, 49, 35, 19, 23, 20, 11, 11, 31, 48, 28, 21, 44, 29]),
 (31,))

In [232]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[31 45 73 18 70 83 78]
 [17 49 24 50 16 93 63]
 [96 50 77 77 77 29 17]
 [88 39 77 77 77 41 11]
 [21 12 77 77 77 50 35]
 [19 23 84 87 20 11 11]
 [31 48 28 21 44 98 29]]


In [233]:
betko8x7

array([[31, 17, 96, 88, 21, 19, 31],
       [45, 49, 50, 39, 12, 23, 48],
       [73, 24, 77, 77, 77, 84, 28],
       [18, 50, 77, 77, 77, 87, 21],
       [70, 16, 77, 77, 77, 20, 44],
       [83, 93, 29, 41, 50, 11, 98],
       [78, 63, 17, 11, 35, 11, 29],
       [40, 10, 40, 73, 87, 38, 76]])

In [234]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [235]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[31, 45, 73, 18, 70, 83, 78, 40],
       [17, 49, 24, 50, 16, 93, 63, 10],
       [96, 50, 27, 43, 76, 29, 17, 40],
       [88, 39, 87, 43, 17, 41, 11, 73],
       [21, 12, 17, 89, 96, 50, 35, 87],
       [19, 23, 84, 87, 20, 11, 11, 38],
       [31, 48, 28, 21, 44, 98, 29, 76]])

In [236]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematinės operacijos ir funkcijos

Su NumPy arrays galima atlikti paprastus aritmetinius veiksmus:

In [237]:
vektorius = np.arange(1,11)

In [238]:
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
vektorius + vektorius

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [240]:
vektorius * vektorius

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [241]:
vektorius / vektorius

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [242]:
vektorius / 0

C:\Users\DELL G5\AppData\Local\Temp\ipykernel_17160\17242066.py:1: RuntimeWarning: divide by zero encountered in divide
  vektorius / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

atkreipkite dėmesį, atlikus dalybą iš 0 gausime begalybes arba nan - not a number. Taip pat galime atlikti veiksmus ir su skaičiais:

In [243]:
vektorius + 1000

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [244]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

ir t.t.

Numpy aplinkoje taip pat galime taikyti įvairias trigonometrines funkcijas ir tt.

In [245]:
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [246]:
np.log(vektorius)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [247]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [248]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [249]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [250]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [251]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[-1807454463,  1894303437,  2073071593],
       [-1614177151,        2401,   291504128],
       [ 1073741824,  1507045888, -1038305055],
       [       7744,  1540507751,        7569],
       [     194481,       20736, -1614177151],
       [  893871739,  1561364439, -1076625408],
       [ -196513505,           0,         784]])

Visas matematines funkcijas galite surasti
[čia](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).

<br>
<br>

# Užduotys:

<br>

## Pirma užduotis:

Sukurkite vektorių su skaičiais nuo 1 iki 9:

In [252]:

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<br>

## Antra užduotis:

Sukurkite vektorių iš 10 nulių:

In [253]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<br>

## Trečia užduotis:

 Sukurkite vektorių iš 10 vienetų:

In [254]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<br>

## Ketvirta užduotis:

Sukurkite vektorių iš 10 ketvertų:

In [255]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

<br>

## Penkta užduotis:

Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100:

In [256]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

<br>

## Šešta užduotis:

Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam:

In [257]:
arr = np.arange(1,26).reshape(5,5)

In [258]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<br>

## Septinta užduotis:

 Iš matricos ištraukite skaičių 12:

In [259]:
arr[2, 1]

12

<br>

## Aštunta užduotis:

 Iš matricos ištraukite paskutinę eilutę:

In [260]:
arr[-1]

array([21, 22, 23, 24, 25])

<br>

## Devinta užduotis:

 Iš matricos ištraukite submatricą:

1, 2, 3<br>
6, 7, 8<br>
11,12,13

In [261]:
arr[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

<br>

## Dešimta užduotis:

Iš matricos ištraukite submatricą:

7, 8, 9, 10<br>
12, 13, 14, 15<br>
17, 18, 19, 20

In [262]:
arr[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

<br>

## Vienuolikta užduotis:

 Iš matricos ištraukite submatricą:

 16, 17, 18<br>
21, 22, 23

In [263]:
arr[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

<br>

## Dvylikta užduotis:

Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam:

In [264]:

randarr = np.random.rand(20)

In [265]:
randarr

array([0.89179209, 0.85796994, 0.96392977, 0.67549862, 0.92010406,
       0.8059909 , 0.13510727, 0.29920157, 0.00477129, 0.52508225,
       0.87467925, 0.96634141, 0.98931004, 0.37182838, 0.48907755,
       0.27662383, 0.47324797, 0.21508788, 0.39594236, 0.0331707 ])

<br>

## Trylikta užduotis:

 Suraskite didžiausią reikšmę masyve ir jos indeksą:

In [266]:
max(randarr)

0.9893100429792976

In [267]:
randarr.argmax()

12

<br>

## Keturiolikta užduotis:

Suraskite mažiausią reikšmę ir jos indeksą:

In [268]:
randarr.min()

0.004771293813020772

In [269]:
randarr.argmin()

8

<br>

## Penkiolikta užduotis:

 Atspausdinkite šios matricos duomenų tipą:

In [270]:
randarr.dtype

dtype('float64')

<br>

## Šešiolikta užduotis:

Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90:

In [271]:
bandymas = np.arange(1,101)

In [272]:
bandymas

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [273]:

bandymas[bandymas > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

<br>

## Septyniolikta užduotis:

 Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius:

In [274]:
bandymas[bandymas % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

<br>

## Aštuoniolikta užduotis:

Sukurkite tokią matricą:

In [ ]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [275]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

<br>

## Devyniolikta užduotis:

Sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [ ]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [276]:
matrica = np.arange(2,1000)

In [277]:
res = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)

In [278]:
res

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

<br>

## Dvidešimta užduotis (BONUS):

* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.

* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.

* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip:<br>
<b>nauja_funkcija = np.vectorize(jūsų_funkcija)<b>.

* Kadangi sąlygos reikšmių traukimui yra bool reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus

In [279]:
testlist = np.arange(1,101)

In [280]:
def is_prime(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True

In [281]:
vis_prime = np.vectorize(is_prime)

In [282]:
testlist[vis_prime(testlist)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])