In [1]:
import numpy as np

In [2]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [3]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


In [6]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [7]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [10]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
np.random.rand(5)

array([0.88136702, 0.02105598, 0.23563319, 0.83667698, 0.12952329])

In [12]:
np.random.rand(5, 5)

array([[0.56914123, 0.50263675, 0.61468623, 0.20515143, 0.45919133],
       [0.76100387, 0.26494096, 0.30320283, 0.7317195 , 0.10987218],
       [0.02707268, 0.58279357, 0.00180188, 0.26450907, 0.33375907],
       [0.16050185, 0.75607055, 0.9100438 , 0.23954819, 0.00151225],
       [0.76045407, 0.63744793, 0.62945374, 0.92731617, 0.77260839]])

In [13]:
np.random.randn(4, 4)

array([[ 0.55429671,  2.26348158, -1.47382749,  0.8146025 ],
       [ 0.68746794,  1.17872189,  0.83264143,  0.32731111],
       [-0.18478308,  0.43820461,  0.80156948, -0.08226728],
       [ 0.38057142,  0.37338412,  0.66131356, -1.12466072]])

In [14]:
np.random.randint(1, 100, (5, 5))

array([[67, 94,  1, 93, 23],
       [64,  3, 96, 65, 95],
       [ 3, 32, 71, 97, 34],
       [39, 62, 15, 30, 79],
       [67, 19, 39, 95, 56]])

In [15]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([76, 57, 66, 77, 99, 49, 87, 84, 72, 31, 37, 85, 11, 34, 53, 35, 22,
       49, 82, 97, 59, 24, 96, 34, 75, 50, 39, 82, 97, 55, 57, 77, 63, 67,
       99, 96, 95, 43, 23, 86, 49, 26, 20, 83, 40, 51, 55, 63, 65, 26, 77,
       61, 61, 78, 62, 99])

In [16]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[76, 57, 66, 77, 99, 49, 87],
       [84, 72, 31, 37, 85, 11, 34],
       [53, 35, 22, 49, 82, 97, 59],
       [24, 96, 34, 75, 50, 39, 82],
       [97, 55, 57, 77, 63, 67, 99],
       [96, 95, 43, 23, 86, 49, 26],
       [20, 83, 40, 51, 55, 63, 65],
       [26, 77, 61, 61, 78, 62, 99]])

In [17]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[76, 84, 53, 24, 97, 96, 20, 26],
       [57, 72, 35, 96, 55, 95, 83, 77],
       [66, 31, 22, 34, 57, 43, 40, 61],
       [77, 37, 49, 75, 77, 23, 51, 61],
       [99, 85, 82, 50, 63, 86, 55, 78],
       [49, 11, 97, 39, 67, 49, 63, 62],
       [87, 34, 59, 82, 99, 26, 65, 99]])

In [18]:
betko7x8.reshape(56)

array([76, 84, 53, 24, 97, 96, 20, 26, 57, 72, 35, 96, 55, 95, 83, 77, 66,
       31, 22, 34, 57, 43, 40, 61, 77, 37, 49, 75, 77, 23, 51, 61, 99, 85,
       82, 50, 63, 86, 55, 78, 49, 11, 97, 39, 67, 49, 63, 62, 87, 34, 59,
       82, 99, 26, 65, 99])

In [19]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

524889:-4.730088178272183, 162316:4.8479284597797365


In [20]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


In [21]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[3 7 6 9 8 3 4 8 4 4]
3 9 [3 4 8 4]


In [22]:
print(betko10[::-1])

[4 4 8 4 3 8 9 6 7 3]


In [23]:
print(betko10[-3:5:-1])

[8 4]


In [24]:
betko10[::2] = 0
print(betko10)

[0 7 0 9 0 3 0 8 0 4]


In [25]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[76 84 53 24 97 96 20]
 [57 72 35 96 55 95 83]
 [66 31 22 34 57 43 40]
 [77 37 49 75 77 23 51]
 [99 85 82 50 63 86 55]
 [49 11 97 39 67 49 63]
 [87 34 59 82 99 26 65]] (7, 7) 75


In [26]:
print(betko7x7[2:5, 2:5])

[[22 34 57]
 [49 75 77]
 [82 50 63]]


In [27]:
senukai = betko7x7 >= 50
print(senukai)

[[ True  True  True False  True  True False]
 [ True  True False  True  True  True  True]
 [ True False False False  True False False]
 [ True False False  True  True False  True]
 [ True  True  True  True  True  True  True]
 [False False  True False  True False  True]
 [ True False  True  True  True False  True]]


In [28]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[76 84 53 97 96 57 72 96 55 95 83 66 57 77 75 77 51 99 85 82 50 63 86 55
 97 67 63 87 59 82 99 65] (32,)


In [29]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([24, 20, 35, 31, 22, 34, 43, 40, 37, 49, 23, 49, 11, 39, 49, 34, 26]),
 (17,))

In [30]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[76 84 53 24 97 96 20]
 [57 72 35 96 55 95 83]
 [66 31 77 77 77 43 40]
 [77 37 77 77 77 23 51]
 [99 85 77 77 77 86 55]
 [49 11 97 39 67 49 63]
 [87 34 59 82 99 26 65]]


In [31]:
betko8x7

array([[76, 57, 66, 77, 99, 49, 87],
       [84, 72, 31, 37, 85, 11, 34],
       [53, 35, 77, 77, 77, 97, 59],
       [24, 96, 77, 77, 77, 39, 82],
       [97, 55, 77, 77, 77, 67, 99],
       [96, 95, 43, 23, 86, 49, 26],
       [20, 83, 40, 51, 55, 63, 65],
       [26, 77, 61, 61, 78, 62, 99]])

In [32]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [33]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[76, 84, 53, 24, 97, 96, 20, 26],
       [57, 72, 35, 96, 55, 95, 83, 77],
       [66, 31, 74, 23, 93, 43, 40, 61],
       [77, 37, 37, 52, 11, 23, 51, 61],
       [99, 85, 13, 65, 93, 86, 55, 78],
       [49, 11, 97, 39, 67, 49, 63, 62],
       [87, 34, 59, 82, 99, 26, 65, 99]])

In [34]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematika

In [35]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [36]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [37]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [38]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [39]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[      192699928576,             592704,          418195493],
       [          10556001,         1934917632,        64339296875],
       [          18974736,           28629151,           29986576],
       [  1235736291547681,        94931877133,            1874161],
       [        9509900499,               7225,            4826809],
       [      678223072849,               1331, 760231058654565217],
       [          57289761,           45435424,      2488651484819]])

In [40]:
eile_4x4 = np.arange(1, 17).reshape(4, 4)
eile_4x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
eile_4x4[1:3, 2:4]

array([[ 7,  8],
       [11, 12]])