In [2]:
import numpy as np

In [3]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [4]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


In [7]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [8]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [11]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
np.random.rand(5)

array([0.34808327, 0.76450921, 0.41170909, 0.65602576, 0.46127987])

In [13]:
np.random.rand(5, 5)

array([[0.24243881, 0.73228381, 0.21628174, 0.66152211, 0.62833004],
       [0.73837891, 0.39277706, 0.60755125, 0.60636212, 0.22268686],
       [0.50349279, 0.02885138, 0.7975096 , 0.60247411, 0.18800944],
       [0.63013813, 0.38734036, 0.66346342, 0.73941945, 0.58534183],
       [0.54115251, 0.78483065, 0.83711374, 0.49974078, 0.77384407]])

In [14]:
np.random.randn(4, 4)

array([[-0.87410212, -1.071328  , -0.46033022,  0.32639798],
       [ 0.2578106 , -0.29377698,  2.82207272,  0.22335176],
       [ 1.17405718, -1.02837501,  0.36955084, -0.16224161],
       [-0.70820734,  1.67586935, -1.44402047,  0.01629314]])

In [15]:
np.random.randint(1, 100, (5, 5))

array([[89, 80, 87, 23, 72],
       [63, 94, 98, 19, 70],
       [ 4, 85, 60,  8, 71],
       [89, 77, 94, 17, 16],
       [66, 12, 11, 35, 12]])

In [16]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([67, 66, 26, 54, 60, 20, 48, 22, 40, 14, 71, 13, 22, 49, 92, 74, 75,
       26, 14, 14, 82, 35, 92, 83, 19, 57, 87, 52, 87, 88, 60, 31, 49, 87,
       61, 15, 92, 44, 72, 34, 94, 11, 26, 79, 24, 64, 40, 84, 58, 77, 80,
       31, 32, 86, 14, 99])

In [17]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[67, 66, 26, 54, 60, 20, 48],
       [22, 40, 14, 71, 13, 22, 49],
       [92, 74, 75, 26, 14, 14, 82],
       [35, 92, 83, 19, 57, 87, 52],
       [87, 88, 60, 31, 49, 87, 61],
       [15, 92, 44, 72, 34, 94, 11],
       [26, 79, 24, 64, 40, 84, 58],
       [77, 80, 31, 32, 86, 14, 99]])

In [18]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[67, 22, 92, 35, 87, 15, 26, 77],
       [66, 40, 74, 92, 88, 92, 79, 80],
       [26, 14, 75, 83, 60, 44, 24, 31],
       [54, 71, 26, 19, 31, 72, 64, 32],
       [60, 13, 14, 57, 49, 34, 40, 86],
       [20, 22, 14, 87, 87, 94, 84, 14],
       [48, 49, 82, 52, 61, 11, 58, 99]])

In [19]:
betko7x8.reshape(56)

array([67, 22, 92, 35, 87, 15, 26, 77, 66, 40, 74, 92, 88, 92, 79, 80, 26,
       14, 75, 83, 60, 44, 24, 31, 54, 71, 26, 19, 31, 72, 64, 32, 60, 13,
       14, 57, 49, 34, 40, 86, 20, 22, 14, 87, 87, 94, 84, 14, 48, 49, 82,
       52, 61, 11, 58, 99])

In [20]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

693139:-4.9260310106369625, 696442:4.659826498322531


In [21]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


In [22]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[2 7 4 4 2 5 4 2 5 5]
2 4 [5 4 2 5]


In [23]:
print(betko10[::-1])

[5 5 2 4 5 2 4 4 7 2]


In [24]:
print(betko10[-3:5:-1])

[2 4]


In [25]:
betko10[::2] = 0
print(betko10)

[0 7 0 4 0 5 0 2 0 5]


In [26]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[67 22 92 35 87 15 26]
 [66 40 74 92 88 92 79]
 [26 14 75 83 60 44 24]
 [54 71 26 19 31 72 64]
 [60 13 14 57 49 34 40]
 [20 22 14 87 87 94 84]
 [48 49 82 52 61 11 58]] (7, 7) 19


In [27]:
print(betko7x7[2:5, 2:5])

[[75 83 60]
 [26 19 31]
 [14 57 49]]


In [28]:
senukai = betko7x7 >= 50
print(senukai)

[[ True False  True False  True False False]
 [ True False  True  True  True  True  True]
 [False False  True  True  True False False]
 [ True  True False False False  True  True]
 [ True False False  True False False False]
 [False False False  True  True  True  True]
 [False False  True  True  True False  True]]


In [29]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[67 92 87 66 74 92 88 92 79 75 83 60 54 71 72 64 60 57 87 87 94 84 82 52
 61 58] (26,)


In [30]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([22, 35, 15, 26, 40, 26, 14, 44, 24, 26, 19, 31, 13, 14, 49, 34, 40,
        20, 22, 14, 48, 49, 11]),
 (23,))

In [31]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[67 22 92 35 87 15 26]
 [66 40 74 92 88 92 79]
 [26 14 77 77 77 44 24]
 [54 71 77 77 77 72 64]
 [60 13 77 77 77 34 40]
 [20 22 14 87 87 94 84]
 [48 49 82 52 61 11 58]]


In [32]:
betko8x7

array([[67, 66, 26, 54, 60, 20, 48],
       [22, 40, 14, 71, 13, 22, 49],
       [92, 74, 77, 77, 77, 14, 82],
       [35, 92, 77, 77, 77, 87, 52],
       [87, 88, 77, 77, 77, 87, 61],
       [15, 92, 44, 72, 34, 94, 11],
       [26, 79, 24, 64, 40, 84, 58],
       [77, 80, 31, 32, 86, 14, 99]])

In [33]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [34]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[67, 22, 92, 35, 87, 15, 26, 77],
       [66, 40, 74, 92, 88, 92, 79, 80],
       [26, 14, 18, 24, 77, 44, 24, 31],
       [54, 71, 18, 50, 57, 72, 64, 32],
       [60, 13, 25, 81, 71, 34, 40, 86],
       [20, 22, 14, 87, 87, 94, 84, 14],
       [48, 49, 82, 52, 61, 11, 58, 99]])

In [39]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematika

In [55]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [56]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [57]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [58]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [64]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[         20151121,     1207269217792,    55784660123648],
       [23762680013799936,             64000,    12151280273024],
       [     208827064576,             38416,         612220032],
       [           157464,              5041,              5832],
       [    2799360000000,             28561,         244140625],
       [             8000,     1207269217792,               196],
       [      12230590464,    33232930569601,          45212176]])