In [2]:
import numpy as np

In [3]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [4]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


In [13]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [14]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [20]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
np.random.rand(5)

array([0.23651123, 0.80097466, 0.17931985, 0.40497414, 0.31496774])

In [32]:
np.random.rand(5, 5)

array([[0.14046455, 0.68518828, 0.01827802, 0.81851879, 0.94261285],
       [0.97425551, 0.06037434, 0.28781546, 0.84150527, 0.98719731],
       [0.84204338, 0.27355879, 0.70480425, 0.80784763, 0.34320828],
       [0.5769031 , 0.06895254, 0.71098766, 0.76807496, 0.15074401],
       [0.68032375, 0.75811634, 0.02675257, 0.35646541, 0.7303687 ]])

In [56]:
np.random.randn(4, 4)

array([[-0.35009713, -0.81910969, -1.85540382,  1.95788379],
       [ 0.72459436, -1.22435256, -0.11397715,  0.29569704],
       [ 1.31154334,  0.90300631, -1.31402735,  1.0386515 ],
       [ 0.5633311 ,  0.74490031,  0.84066376,  0.97075356]])

In [69]:
np.random.randint(1, 100, (5, 5))

array([[99, 16, 10, 49, 26],
       [38, 37, 20, 16, 20],
       [23, 76, 94, 30, 58],
       [ 6, 97, 28, 59, 74],
       [39, 11, 79,  1, 35]])

In [96]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([41, 46, 84, 10, 91, 71, 40, 81, 36, 77, 23, 24, 22, 23, 40, 52, 80,
       92, 86, 23, 82, 69, 46, 88, 14, 55, 83, 71, 23, 37, 93, 56, 97, 98,
       76, 61, 54, 67, 28, 19, 82, 27, 71, 46, 56, 91, 19, 95, 65, 80, 16,
       50, 66, 56, 17, 88])

In [97]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[41, 46, 84, 10, 91, 71, 40],
       [81, 36, 77, 23, 24, 22, 23],
       [40, 52, 80, 92, 86, 23, 82],
       [69, 46, 88, 14, 55, 83, 71],
       [23, 37, 93, 56, 97, 98, 76],
       [61, 54, 67, 28, 19, 82, 27],
       [71, 46, 56, 91, 19, 95, 65],
       [80, 16, 50, 66, 56, 17, 88]])

In [98]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[41, 81, 40, 69, 23, 61, 71, 80],
       [46, 36, 52, 46, 37, 54, 46, 16],
       [84, 77, 80, 88, 93, 67, 56, 50],
       [10, 23, 92, 14, 56, 28, 91, 66],
       [91, 24, 86, 55, 97, 19, 19, 56],
       [71, 22, 23, 83, 98, 82, 95, 17],
       [40, 23, 82, 71, 76, 27, 65, 88]])

In [100]:
betko7x8.reshape(56)

array([41, 81, 40, 69, 23, 61, 71, 80, 46, 36, 52, 46, 37, 54, 46, 16, 84,
       77, 80, 88, 93, 67, 56, 50, 10, 23, 92, 14, 56, 28, 91, 66, 91, 24,
       86, 55, 97, 19, 19, 56, 71, 22, 23, 83, 98, 82, 95, 17, 40, 23, 82,
       71, 76, 27, 65, 88])

In [128]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

205635:-4.692440312745636, 937388:4.42616141883213


In [131]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


In [135]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[4 8 3 5 8 4 3 9 8 6]
4 5 [4 3 9 8]


In [136]:
print(betko10[::-1])

[6 8 9 3 4 8 5 3 8 4]


In [141]:
print(betko10[-3:5:-1])

[9 3]


In [142]:
betko10[::2] = 0
print(betko10)

[0 8 0 5 0 4 0 9 0 6]


In [146]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[41 81 40 69 23 61 71]
 [46 36 52 46 37 54 46]
 [84 77 80 88 93 67 56]
 [10 23 92 14 56 28 91]
 [91 24 86 55 97 19 19]
 [71 22 23 83 98 82 95]
 [40 23 82 71 76 27 65]] (7, 7) 14


In [147]:
print(betko7x7[2:5, 2:5])

[[80 88 93]
 [92 14 56]
 [86 55 97]]


In [148]:
senukai = betko7x7 >= 50
print(senukai)

[[False  True False  True False  True  True]
 [False False  True False False  True False]
 [ True  True  True  True  True  True  True]
 [False False  True False  True False  True]
 [ True False  True  True  True False False]
 [ True False False  True  True  True  True]
 [False False  True  True  True False  True]]


In [150]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[81 69 61 71 52 54 84 77 80 88 93 67 56 92 56 91 91 86 55 97 71 83 98 82
 95 82 71 76 65] (29,)


In [152]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([41, 40, 23, 46, 36, 46, 37, 46, 10, 23, 14, 28, 24, 19, 19, 22, 23,
        40, 23, 27]),
 (20,))

In [153]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[41 81 40 69 23 61 71]
 [46 36 52 46 37 54 46]
 [84 77 77 77 77 67 56]
 [10 23 77 77 77 28 91]
 [91 24 77 77 77 19 19]
 [71 22 23 83 98 82 95]
 [40 23 82 71 76 27 65]]


In [154]:
betko8x7

array([[41, 46, 84, 10, 91, 71, 40],
       [81, 36, 77, 23, 24, 22, 23],
       [40, 52, 77, 77, 77, 23, 82],
       [69, 46, 77, 77, 77, 83, 71],
       [23, 37, 77, 77, 77, 98, 76],
       [61, 54, 67, 28, 19, 82, 27],
       [71, 46, 56, 91, 19, 95, 65],
       [80, 16, 50, 66, 56, 17, 88]])

In [156]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [159]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[41, 81, 40, 69, 23, 61, 71, 80],
       [46, 36, 52, 46, 37, 54, 46, 16],
       [84, 77, 21, 75, 51, 67, 56, 50],
       [10, 23, 21, 43, 85, 28, 91, 66],
       [91, 24, 86, 18, 17, 19, 19, 56],
       [71, 22, 23, 83, 98, 82, 95, 17],
       [40, 23, 82, 71, 76, 27, 65, 88]])

In [160]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])