In [1]:
import numpy as np

In [2]:
skaiciai = [4, 3, 5, 1, 7, 2]
np_skaiciai = np.array(skaiciai)
print(skaiciai)
print(np_skaiciai)

[4, 3, 5, 1, 7, 2]
[4 3 5 1 7 2]


In [3]:
keypad = [
    [7, 8, 9],
    [4, 5, 6],
    [1, 2, 3]
]
matrix_keypad = np.array(keypad)
print(matrix_keypad)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
eile = np.arange(100)
print(eile)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.linspace(10, 30, 17)

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ,
       21.25, 22.5 , 23.75, 25.  , 26.25, 27.5 , 28.75, 30.  ])

In [13]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(10)

array([0.40917237, 0.82667931, 0.62360255, 0.52274379, 0.52951637,
       0.53433304, 0.5635563 , 0.00248536, 0.71134719, 0.48973881])

In [15]:
np.random.rand(3, 3)

array([[0.96798085, 0.01438587, 0.66384558],
       [0.48633602, 0.09120087, 0.82643269],
       [0.99138424, 0.66358066, 0.07050574]])

In [30]:
teleloto = np.random.randint(10, 99, (5, 5))
teleloto

array([[26, 83, 53, 83, 21],
       [57, 51, 76, 44, 55],
       [68, 33, 77, 74, 51],
       [90, 74, 49, 83, 75],
       [57, 33, 41, 60, 35]])

In [35]:
sem = np.random.randint(10, 99, 60)
sem

array([69, 39, 39, 66, 52, 91, 36, 71, 44, 81, 26, 88, 42, 59, 93, 92, 89,
       18, 12, 83, 45, 84, 13, 26, 32, 61, 64, 76, 56, 52, 16, 38, 84, 68,
       26, 44, 15, 81, 64, 65, 97, 91, 96, 42, 41, 16, 18, 53, 28, 57, 50,
       80, 15, 29, 55, 87, 12, 37, 21, 12])

In [42]:
sem6x10 = sem.reshape(6, 10)

In [37]:
sem.reshape(12, 5)

array([[69, 39, 39, 66, 52],
       [91, 36, 71, 44, 81],
       [26, 88, 42, 59, 93],
       [92, 89, 18, 12, 83],
       [45, 84, 13, 26, 32],
       [61, 64, 76, 56, 52],
       [16, 38, 84, 68, 26],
       [44, 15, 81, 64, 65],
       [97, 91, 96, 42, 41],
       [16, 18, 53, 28, 57],
       [50, 80, 15, 29, 55],
       [87, 12, 37, 21, 12]])

In [38]:
sem.min(), sem.max()

(12, 97)

In [39]:
sem.argmin(), sem.argmax()

(18, 40)

In [43]:
sem6x10.shape

(6, 10)

In [44]:
sem6x10.dtype

dtype('int64')

In [46]:
sem[18], sem[sem.argmax()]

(12, 97)

In [47]:
sem[10:20]

array([26, 88, 42, 59, 93, 92, 89, 18, 12, 83])

In [48]:
sem[::10]

array([69, 26, 45, 16, 97, 50])

In [49]:
sem[1::10]

array([39, 88, 84, 38, 91, 80])

In [55]:
dirty_sem = sem6x10.copy()
dirty_sem[3, ] = 77
dirty_sem

array([[69, 39, 39, 66, 52, 91, 36, 71, 44, 81],
       [26, 88, 42, 59, 93, 92, 89, 18, 12, 83],
       [45, 84, 13, 26, 32, 61, 64, 76, 56, 52],
       [77, 77, 77, 77, 77, 77, 77, 77, 77, 77],
       [97, 91, 96, 42, 41, 16, 18, 53, 28, 57],
       [50, 80, 15, 29, 55, 87, 12, 37, 21, 12]])

In [57]:
dirty_sem = sem.copy()
dirty_sem[3::10] = 77
dirty_sem = dirty_sem.reshape(6, 10)
dirty_sem

array([[69, 39, 39, 77, 52, 91, 36, 71, 44, 81],
       [26, 88, 42, 77, 93, 92, 89, 18, 12, 83],
       [45, 84, 13, 77, 32, 61, 64, 76, 56, 52],
       [16, 38, 84, 77, 26, 44, 15, 81, 64, 65],
       [97, 91, 96, 77, 41, 16, 18, 53, 28, 57],
       [50, 80, 15, 77, 55, 87, 12, 37, 21, 12]])

In [58]:
dirty_sem[2, 4]

32

In [59]:
dirty_sem[2:-2, 2:-2]

array([[13, 77, 32, 61, 64, 76],
       [84, 77, 26, 44, 15, 81]])

In [61]:
sem6x10 > 50

array([[ True, False, False,  True,  True,  True, False,  True, False,
         True],
       [False,  True, False,  True,  True,  True,  True, False, False,
         True],
       [False,  True, False, False, False,  True,  True,  True,  True,
         True],
       [False, False,  True,  True, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True, False,
         True],
       [False,  True, False, False,  True,  True, False, False, False,
        False]])

In [62]:
sem6x10[sem6x10 > 50]

array([69, 66, 52, 91, 71, 81, 88, 59, 93, 92, 89, 83, 84, 61, 64, 76, 56,
       52, 84, 68, 81, 64, 65, 97, 91, 96, 53, 57, 80, 55, 87])

In [64]:
tiesos_matrica = sem > 50
sem[tiesos_matrica]

array([69, 66, 52, 91, 71, 81, 88, 59, 93, 92, 89, 83, 84, 61, 64, 76, 56,
       52, 84, 68, 81, 64, 65, 97, 91, 96, 53, 57, 80, 55, 87])

In [73]:
dirty_sem
dirty_fragment = dirty_sem[2:3, 1:-3]
dirty_fragment[:] = 3
dirty_sem

array([[69, 39, 39, 77, 52, 91, 36, 71, 44, 81],
       [26, 88, 42, 77, 93, 92, 89, 18, 12, 83],
       [45,  3,  3,  3,  3,  3,  3, 76, 56, 52],
       [16, 38, 84, 77, 26, 44, 15, 81, 64, 65],
       [97, 91, 96, 77, 41, 16, 18, 53, 28, 57],
       [50, 80, 15, 77, 55, 87, 12, 37, 21, 12]])

In [75]:
sem6x10 - dirty_sem

array([[  0,   0,   0, -11,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, -18,   0,   0,   0,   0,   0,   0],
       [  0,  81,  10,  23,  29,  58,  61,   0,   0,   0],
       [  0,   0,   0,  -9,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, -35,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, -48,   0,   0,   0,   0,   0,   0]])

In [76]:
dirty_sem // 10

array([[6, 3, 3, 7, 5, 9, 3, 7, 4, 8],
       [2, 8, 4, 7, 9, 9, 8, 1, 1, 8],
       [4, 0, 0, 0, 0, 0, 0, 7, 5, 5],
       [1, 3, 8, 7, 2, 4, 1, 8, 6, 6],
       [9, 9, 9, 7, 4, 1, 1, 5, 2, 5],
       [5, 8, 1, 7, 5, 8, 1, 3, 2, 1]])

In [80]:
np.log((sem // 10) ** 5)

array([ 8.95879735,  5.49306144,  5.49306144,  8.95879735,  8.04718956,
       10.98612289,  5.49306144,  9.72955075,  6.93147181, 10.39720771,
        3.4657359 , 10.39720771,  6.93147181,  8.04718956, 10.98612289,
       10.98612289, 10.39720771,  0.        ,  0.        , 10.39720771,
        6.93147181, 10.39720771,  0.        ,  3.4657359 ,  5.49306144,
        8.95879735,  8.95879735,  9.72955075,  8.04718956,  8.04718956,
        0.        ,  5.49306144, 10.39720771,  8.95879735,  3.4657359 ,
        6.93147181,  0.        , 10.39720771,  8.95879735,  8.95879735,
       10.98612289, 10.98612289, 10.98612289,  6.93147181,  6.93147181,
        0.        ,  0.        ,  8.04718956,  3.4657359 ,  8.04718956,
        8.04718956, 10.39720771,  0.        ,  3.4657359 ,  8.04718956,
       10.39720771,  0.        ,  5.49306144,  3.4657359 ,  0.        ])