In [2]:
import pandas as pd
import numpy as np

In [3]:
people = "Geras Linxmas Nutrukes Destytojas".split()
s_people = pd.Series(people)
print(s_people)

0         Geras
1       Linxmas
2      Nutrukes
3    Destytojas
dtype: object


In [4]:
amziai = [18, 25, 30, 40]
s_ages = pd.Series(amziai, people)
print(s_ages)

Geras         18
Linxmas       25
Nutrukes      30
Destytojas    40
dtype: int64


In [5]:
s_amziai2 = pd.Series([10, 25, 35, 40], "Geras Linxmas Naminis Destytojas".split())
s_amziai2

Geras         10
Linxmas       25
Naminis       35
Destytojas    40
dtype: int64

In [6]:
s_ages['Destytojas']

40

In [7]:
s_ages + s_amziai2

Destytojas    80.0
Geras         28.0
Linxmas       50.0
Naminis        NaN
Nutrukes       NaN
dtype: float64

In [8]:
cities = 'Vilnius Kaunas Šiauliai Klaipėda'.split()
s_cities = pd.Series(cities, people)
s_cities

Geras          Vilnius
Linxmas         Kaunas
Nutrukes      Šiauliai
Destytojas    Klaipėda
dtype: object

In [9]:
random_array = np.random.randint(10, 99, 30)
print(random_array)
shape = 5, 6
random_matrix = random_array.reshape(shape)
print(random_matrix)
df_randint = pd.DataFrame(
    data=random_matrix,
    index='a b c d e'.split(),
    columns='U V W X Y Z'.split(),
)
df_randint

[12 55 73 17 34 40 54 47 48 49 16 73 68 27 54 12 65 21 48 96 55 41 54 98
 30 96 85 32 61 50]
[[12 55 73 17 34 40]
 [54 47 48 49 16 73]
 [68 27 54 12 65 21]
 [48 96 55 41 54 98]
 [30 96 85 32 61 50]]


U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
c  68  27  54  12  65  21
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [10]:
df_randint['X']

a    17
b    49
c    12
d    41
e    32
Name: X, dtype: int64

In [11]:
df_randint[['X', 'Z', 'U']]

X   Z   U
a  17  40  12
b  49  73  54
c  12  21  68
d  41  98  48
e  32  50  30

In [12]:
df_randint['T'] = np.random.randint(10, 50, 5)
df_randint

U   V   W   X   Y   Z   T
a  12  55  73  17  34  40  15
b  54  47  48  49  16  73  26
c  68  27  54  12  65  21  39
d  48  96  55  41  54  98  29
e  30  96  85  32  61  50  13

In [13]:
df_randint.drop('T', axis=1, inplace=True)
df_randint

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
c  68  27  54  12  65  21
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [14]:
df_randint.drop('c')

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [15]:
df_randint.drop(['c', 'e'])

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
d  48  96  55  41  54  98

In [16]:
eilute = df_randint.loc['c']
print(eilute, type(eilute))

U    68
V    27
W    54
X    12
Y    65
Z    21
Name: c, dtype: int64 <class 'pandas.core.series.Series'>


In [17]:
df_randint.iloc[3]

U    48
V    96
W    55
X    41
Y    54
Z    98
Name: d, dtype: int64

In [18]:
df_randint.loc['c', 'U']

68

In [19]:
df_randint.loc[['a', 'c', 'e'], ['X', 'Y', 'Z']]

X   Y   Z
a  17  34  40
c  12  65  21
e  32  61  50

In [20]:
df_randint['X']['e']

32

In [21]:
df_randint[df_randint > 50]

U     V     W   X     Y     Z
a   NaN  55.0  73.0 NaN   NaN   NaN
b  54.0   NaN   NaN NaN   NaN  73.0
c  68.0   NaN  54.0 NaN  65.0   NaN
d   NaN  96.0  55.0 NaN  54.0  98.0
e   NaN  96.0  85.0 NaN  61.0   NaN

In [22]:
df_randint[df_randint['X'] > 70][['V', 'Z']]

Empty DataFrame
Columns: [V, Z]
Index: []

In [23]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)]

Empty DataFrame
Columns: [U, V, W, X, Y, Z]
Index: []

In [24]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)][['X', 'Y', 'U']]

Empty DataFrame
Columns: [X, Y, U]
Index: []

In [25]:
df_randint.reset_index()

index   U   V   W   X   Y   Z
0     a  12  55  73  17  34  40
1     b  54  47  48  49  16  73
2     c  68  27  54  12  65  21
3     d  48  96  55  41  54  98
4     e  30  96  85  32  61  50

In [26]:
new_index = 'Vilniuas Kaunas Klaipeda Siauliai Panevezys'.split()
new_index

['Vilniuas', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys']

In [27]:
df_randint['miestai'] = new_index
df_randint

U   V   W   X   Y   Z    miestai
a  12  55  73  17  34  40   Vilniuas
b  54  47  48  49  16  73     Kaunas
c  68  27  54  12  65  21   Klaipeda
d  48  96  55  41  54  98   Siauliai
e  30  96  85  32  61  50  Panevezys

In [28]:
df_randint.set_index('miestai', inplace=True)

In [29]:
df_randint

U   V   W   X   Y   Z
miestai                          
Vilniuas   12  55  73  17  34  40
Kaunas     54  47  48  49  16  73
Klaipeda   68  27  54  12  65  21
Siauliai   48  96  55  41  54  98
Panevezys  30  96  85  32  61  50

In [30]:
df_people = pd.concat([s_ages, s_cities], axis=1)
df_people.columns = ['amzius', 'miestas']
df_people

amzius   miestas
Geras           18   Vilnius
Linxmas         25    Kaunas
Nutrukes        30  Šiauliai
Destytojas      40  Klaipėda

In [31]:
df_miestai = pd.read_csv('miestai_isvalyti.csv', encoding='utf-8')
df_miestai

Miestas    2019    2011    2001    1989    1979    1970    1959   
0        Vilnius  540919  535631  542287  576747  475825  370153  236100  \
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  
0    167400  154532  
1     92446   70920  
2     35845   20100  
3     21387   16128  
4     19197   12968  
..      ...     ...  
98     1164    1278  
99     1041    1546  
100    1741       0  
101    1252    1000  
102     637       0  

[103 rows x 10 columns]

In [32]:
df_randint

U   V   W   X   Y   Z
miestai                          
Vilniuas   12  55  73  17  34  40
Kaunas     54  47  48  49  16  73
Klaipeda   68  27  54  12  65  21
Siauliai   48  96  55  41  54  98
Panevezys  30  96  85  32  61  50

In [36]:
dideli = df_randint[df_randint > 30]
dideli

U     V   W     X     Y     Z
miestai                                    
Vilniuas    NaN  55.0  73   NaN  34.0  40.0
Kaunas     54.0  47.0  48  49.0   NaN  73.0
Klaipeda   68.0   NaN  54   NaN  65.0   NaN
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   NaN  96.0  85  32.0  61.0  50.0

In [37]:
dideli.isnull()

U      V      W      X      Y      Z
miestai                                            
Vilniuas    True  False  False   True  False  False
Kaunas     False  False  False  False   True  False
Klaipeda   False   True  False   True  False   True
Siauliai   False  False  False  False  False  False
Panevezys   True  False  False  False  False  False

In [38]:
dideli.isnull().sum()

U    2
V    1
W    0
X    2
Y    1
Z    1
dtype: int64

In [40]:
dideli['X'].isnull()

miestai
Vilniuas      True
Kaunas       False
Klaipeda      True
Siauliai     False
Panevezys    False
Name: X, dtype: bool

In [41]:
dideli['X'].isnull().sum()

2

In [42]:
dideli.dropna()

U     V   W     X     Y     Z
miestai                                   
Siauliai  48.0  96.0  55  41.0  54.0  98.0

In [43]:
dideli.dropna(axis=1)

W
miestai      
Vilniuas   73
Kaunas     48
Klaipeda   54
Siauliai   55
Panevezys  85

In [44]:
dideli.dropna(thresh=5)

U     V   W     X     Y     Z
miestai                                    
Kaunas     54.0  47.0  48  49.0   NaN  73.0
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   NaN  96.0  85  32.0  61.0  50.0

In [45]:
dideli.dropna(thresh=4, axis=1)

V   W     Y     Z
miestai                        
Vilniuas   55.0  73  34.0  40.0
Kaunas     47.0  48   NaN  73.0
Klaipeda    NaN  54  65.0   NaN
Siauliai   96.0  55  54.0  98.0
Panevezys  96.0  85  61.0  50.0

In [46]:
dideli.fillna('permazas')

U         V   W         X         Y         Z
miestai                                                        
Vilniuas   permazas      55.0  73  permazas      34.0      40.0
Kaunas         54.0      47.0  48      49.0  permazas      73.0
Klaipeda       68.0  permazas  54  permazas      65.0  permazas
Siauliai       48.0      96.0  55      41.0      54.0      98.0
Panevezys  permazas      96.0  85      32.0      61.0      50.0

In [47]:
dideli.fillna(0)

U     V   W     X     Y     Z
miestai                                    
Vilniuas    0.0  55.0  73   0.0  34.0  40.0
Kaunas     54.0  47.0  48  49.0   0.0  73.0
Klaipeda   68.0   0.0  54   0.0  65.0   0.0
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   0.0  96.0  85  32.0  61.0  50.0

In [49]:
dideli.fillna(value=dideli.mean())

U     V   W          X     Y      Z
miestai                                               
Vilniuas   56.666667  55.0  73  40.666667  34.0  40.00
Kaunas     54.000000  47.0  48  49.000000  53.5  73.00
Klaipeda   68.000000  73.5  54  40.666667  65.0  65.25
Siauliai   48.000000  96.0  55  41.000000  54.0  98.00
Panevezys  56.666667  96.0  85  32.000000  61.0  50.00

In [53]:
dideli['U'].fillna(value=dideli['U'].mean())

miestai
Vilniuas     56.666667
Kaunas       54.000000
Klaipeda     68.000000
Siauliai     48.000000
Panevezys    56.666667
Name: U, dtype: float64