In [111]:
import pandas as pd
import numpy as np

In [112]:
people = "Geras Linxmas Nutrukes Destytojas".split()
s_people = pd.Series(people)
print(s_people)

0         Geras
1       Linxmas
2      Nutrukes
3    Destytojas
dtype: object


In [113]:
amziai = [18, 25, 30, 40]
s_ages = pd.Series(amziai, people)
print(s_ages)

Geras         18
Linxmas       25
Nutrukes      30
Destytojas    40
dtype: int64


In [114]:
s_amziai2 = pd.Series([10, 25, 35, 40], "Geras Linxmas Naminis Destytojas".split())
s_amziai2

Geras         10
Linxmas       25
Naminis       35
Destytojas    40
dtype: int64

In [115]:
s_ages['Destytojas']

40

In [116]:
s_ages + s_amziai2

Destytojas    80.0
Geras         28.0
Linxmas       50.0
Naminis        NaN
Nutrukes       NaN
dtype: float64

In [117]:
cities = 'Vilnius Kaunas Šiauliai Klaipėda'.split()
s_cities = pd.Series(cities, people)
s_cities

Geras          Vilnius
Linxmas         Kaunas
Nutrukes      Šiauliai
Destytojas    Klaipėda
dtype: object

In [118]:
random_array = np.random.randint(10, 99, 30)
print(random_array)
shape = 5, 6
random_matrix = random_array.reshape(shape)
print(random_matrix)
df_randint = pd.DataFrame(
    data=random_matrix,
    index='a b c d e'.split(),
    columns='U V W X Y Z'.split(),
)
df_randint

[66 24 15 91 40 51 81 28 77 83 18 94 11 64 38 66 68 15 96 43 49 90 14 49
 39 39 18 18 32 79]
[[66 24 15 91 40 51]
 [81 28 77 83 18 94]
 [11 64 38 66 68 15]
 [96 43 49 90 14 49]
 [39 39 18 18 32 79]]


U   V   W   X   Y   Z
a  66  24  15  91  40  51
b  81  28  77  83  18  94
c  11  64  38  66  68  15
d  96  43  49  90  14  49
e  39  39  18  18  32  79

In [119]:
df_randint['X']

a    91
b    83
c    66
d    90
e    18
Name: X, dtype: int64

In [120]:
df_randint[['X', 'Z', 'U']]

X   Z   U
a  91  51  66
b  83  94  81
c  66  15  11
d  90  49  96
e  18  79  39

In [121]:
df_randint['T'] = np.random.randint(10, 50, 5)
df_randint

U   V   W   X   Y   Z   T
a  66  24  15  91  40  51  15
b  81  28  77  83  18  94  35
c  11  64  38  66  68  15  34
d  96  43  49  90  14  49  29
e  39  39  18  18  32  79  48

In [122]:
df_randint.drop('T', axis=1, inplace=True)
df_randint

U   V   W   X   Y   Z
a  66  24  15  91  40  51
b  81  28  77  83  18  94
c  11  64  38  66  68  15
d  96  43  49  90  14  49
e  39  39  18  18  32  79

In [123]:
df_randint.drop('c')

U   V   W   X   Y   Z
a  66  24  15  91  40  51
b  81  28  77  83  18  94
d  96  43  49  90  14  49
e  39  39  18  18  32  79

In [124]:
df_randint.drop(['c', 'e'])

U   V   W   X   Y   Z
a  66  24  15  91  40  51
b  81  28  77  83  18  94
d  96  43  49  90  14  49

In [125]:
eilute = df_randint.loc['c']
print(eilute, type(eilute))

U    11
V    64
W    38
X    66
Y    68
Z    15
Name: c, dtype: int64 <class 'pandas.core.series.Series'>


In [126]:
df_randint.iloc[3]

U    96
V    43
W    49
X    90
Y    14
Z    49
Name: d, dtype: int64

In [127]:
df_randint.loc['c', 'U']

11

In [128]:
df_randint.loc[['a', 'c', 'e'], ['X', 'Y', 'Z']]

X   Y   Z
a  91  40  51
c  66  68  15
e  18  32  79

In [129]:
df_randint['X']['e']

18

In [130]:
df_randint[df_randint > 50]

U     V     W     X     Y     Z
a  66.0   NaN   NaN  91.0   NaN  51.0
b  81.0   NaN  77.0  83.0   NaN  94.0
c   NaN  64.0   NaN  66.0  68.0   NaN
d  96.0   NaN   NaN  90.0   NaN   NaN
e   NaN   NaN   NaN   NaN   NaN  79.0

In [132]:
df_randint[df_randint['X'] > 70][['V', 'Z']]

V   Z
a  24  51
b  28  94
d  43  49

In [134]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)]

U   V   W   X   Y   Z
a  66  24  15  91  40  51
b  81  28  77  83  18  94
d  96  43  49  90  14  49

In [136]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)][['X', 'Y', 'U']]

X   Y   U
a  91  40  66
b  83  18  81
d  90  14  96

In [137]:
df_randint.reset_index()

index   U   V   W   X   Y   Z
0     a  66  24  15  91  40  51
1     b  81  28  77  83  18  94
2     c  11  64  38  66  68  15
3     d  96  43  49  90  14  49
4     e  39  39  18  18  32  79

In [138]:
new_index = 'Vilniuas Kaunas Klaipeda Siauliai Panevezys'.split()
new_index

['Vilniuas', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys']

In [139]:
df_randint['miestai'] = new_index
df_randint

U   V   W   X   Y   Z    miestai
a  66  24  15  91  40  51   Vilniuas
b  81  28  77  83  18  94     Kaunas
c  11  64  38  66  68  15   Klaipeda
d  96  43  49  90  14  49   Siauliai
e  39  39  18  18  32  79  Panevezys

In [142]:
df_randint.set_index('miestai', inplace=True)

In [143]:
df_randint

U   V   W   X   Y   Z
miestai                          
Vilniuas   66  24  15  91  40  51
Kaunas     81  28  77  83  18  94
Klaipeda   11  64  38  66  68  15
Siauliai   96  43  49  90  14  49
Panevezys  39  39  18  18  32  79

In [149]:
df_people = pd.concat([s_ages, s_cities], axis=1)
df_people.columns = ['amzius', 'miestas']
df_people

amzius   miestas
Geras           18   Vilnius
Linxmas         25    Kaunas
Nutrukes        30  Šiauliai
Destytojas      40  Klaipėda