In [2]:
import pandas as pd
import numpy as np

In [3]:
people = "Geras Linxmas Nutrukes Destytojas".split()
s_people = pd.Series(people)
print(s_people)

0         Geras
1       Linxmas
2      Nutrukes
3    Destytojas
dtype: object


In [4]:
amziai = [18, 25, 30, 40]
s_ages = pd.Series(amziai, people)
print(s_ages)

Geras         18
Linxmas       25
Nutrukes      30
Destytojas    40
dtype: int64


In [5]:
s_amziai2 = pd.Series([10, 25, 35, 40], "Geras Linxmas Naminis Destytojas".split())
s_amziai2

Geras         10
Linxmas       25
Naminis       35
Destytojas    40
dtype: int64

In [6]:
s_ages['Destytojas']

40

In [7]:
s_ages + s_amziai2

Destytojas    80.0
Geras         28.0
Linxmas       50.0
Naminis        NaN
Nutrukes       NaN
dtype: float64

In [8]:
cities = 'Vilnius Kaunas Šiauliai Klaipėda'.split()
s_cities = pd.Series(cities, people)
s_cities

Geras          Vilnius
Linxmas         Kaunas
Nutrukes      Šiauliai
Destytojas    Klaipėda
dtype: object

In [9]:
random_array = np.random.randint(10, 99, 30)
print(random_array)
shape = 5, 6
random_matrix = random_array.reshape(shape)
print(random_matrix)
df_randint = pd.DataFrame(
    data=random_matrix,
    index='a b c d e'.split(),
    columns='U V W X Y Z'.split(),
)
df_randint

[12 55 73 17 34 40 54 47 48 49 16 73 68 27 54 12 65 21 48 96 55 41 54 98
 30 96 85 32 61 50]
[[12 55 73 17 34 40]
 [54 47 48 49 16 73]
 [68 27 54 12 65 21]
 [48 96 55 41 54 98]
 [30 96 85 32 61 50]]


U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
c  68  27  54  12  65  21
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [10]:
df_randint['X']

a    17
b    49
c    12
d    41
e    32
Name: X, dtype: int64

In [11]:
df_randint[['X', 'Z', 'U']]

X   Z   U
a  17  40  12
b  49  73  54
c  12  21  68
d  41  98  48
e  32  50  30

In [12]:
df_randint['T'] = np.random.randint(10, 50, 5)
df_randint

U   V   W   X   Y   Z   T
a  12  55  73  17  34  40  15
b  54  47  48  49  16  73  26
c  68  27  54  12  65  21  39
d  48  96  55  41  54  98  29
e  30  96  85  32  61  50  13

In [13]:
df_randint.drop('T', axis=1, inplace=True)
df_randint

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
c  68  27  54  12  65  21
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [14]:
df_randint.drop('c')

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
d  48  96  55  41  54  98
e  30  96  85  32  61  50

In [15]:
df_randint.drop(['c', 'e'])

U   V   W   X   Y   Z
a  12  55  73  17  34  40
b  54  47  48  49  16  73
d  48  96  55  41  54  98

In [16]:
eilute = df_randint.loc['c']
print(eilute, type(eilute))

U    68
V    27
W    54
X    12
Y    65
Z    21
Name: c, dtype: int64 <class 'pandas.core.series.Series'>


In [17]:
df_randint.iloc[3]

U    48
V    96
W    55
X    41
Y    54
Z    98
Name: d, dtype: int64

In [18]:
df_randint.loc['c', 'U']

68

In [19]:
df_randint.loc[['a', 'c', 'e'], ['X', 'Y', 'Z']]

X   Y   Z
a  17  34  40
c  12  65  21
e  32  61  50

In [20]:
df_randint['X']['e']

32

In [21]:
df_randint[df_randint > 50]

U     V     W   X     Y     Z
a   NaN  55.0  73.0 NaN   NaN   NaN
b  54.0   NaN   NaN NaN   NaN  73.0
c  68.0   NaN  54.0 NaN  65.0   NaN
d   NaN  96.0  55.0 NaN  54.0  98.0
e   NaN  96.0  85.0 NaN  61.0   NaN

In [22]:
df_randint[df_randint['X'] > 70][['V', 'Z']]

Empty DataFrame
Columns: [V, Z]
Index: []

In [23]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)]

Empty DataFrame
Columns: [U, V, W, X, Y, Z]
Index: []

In [24]:
df_randint[(df_randint['X'] > 50) & (df_randint['Y'] < 50)][['X', 'Y', 'U']]

Empty DataFrame
Columns: [X, Y, U]
Index: []

In [25]:
df_randint.reset_index()

index   U   V   W   X   Y   Z
0     a  12  55  73  17  34  40
1     b  54  47  48  49  16  73
2     c  68  27  54  12  65  21
3     d  48  96  55  41  54  98
4     e  30  96  85  32  61  50

In [26]:
new_index = 'Vilniuas Kaunas Klaipeda Siauliai Panevezys'.split()
new_index

['Vilniuas', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys']

In [27]:
df_randint['miestai'] = new_index
df_randint

U   V   W   X   Y   Z    miestai
a  12  55  73  17  34  40   Vilniuas
b  54  47  48  49  16  73     Kaunas
c  68  27  54  12  65  21   Klaipeda
d  48  96  55  41  54  98   Siauliai
e  30  96  85  32  61  50  Panevezys

In [28]:
df_randint.set_index('miestai', inplace=True)

In [29]:
df_randint

U   V   W   X   Y   Z
miestai                          
Vilniuas   12  55  73  17  34  40
Kaunas     54  47  48  49  16  73
Klaipeda   68  27  54  12  65  21
Siauliai   48  96  55  41  54  98
Panevezys  30  96  85  32  61  50

In [30]:
df_people = pd.concat([s_ages, s_cities], axis=1)
df_people.columns = ['amzius', 'miestas']
df_people

amzius   miestas
Geras           18   Vilnius
Linxmas         25    Kaunas
Nutrukes        30  Šiauliai
Destytojas      40  Klaipėda

In [31]:
df_miestai = pd.read_csv('miestai_isvalyti.csv', encoding='utf-8')
df_miestai

Miestas    2019    2011    2001    1989    1979    1970    1959   
0        Vilnius  540919  535631  542287  576747  475825  370153  236100  \
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  
0    167400  154532  
1     92446   70920  
2     35845   20100  
3     21387   16128  
4     19197   12968  
..      ...     ...  
98     1164    1278  
99     1041    1546  
100    1741       0  
101    1252    1000  
102     637       0  

[103 rows x 10 columns]

In [32]:
df_randint

U   V   W   X   Y   Z
miestai                          
Vilniuas   12  55  73  17  34  40
Kaunas     54  47  48  49  16  73
Klaipeda   68  27  54  12  65  21
Siauliai   48  96  55  41  54  98
Panevezys  30  96  85  32  61  50

In [36]:
dideli = df_randint[df_randint > 30]
dideli

U     V   W     X     Y     Z
miestai                                    
Vilniuas    NaN  55.0  73   NaN  34.0  40.0
Kaunas     54.0  47.0  48  49.0   NaN  73.0
Klaipeda   68.0   NaN  54   NaN  65.0   NaN
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   NaN  96.0  85  32.0  61.0  50.0

In [37]:
dideli.isnull()

U      V      W      X      Y      Z
miestai                                            
Vilniuas    True  False  False   True  False  False
Kaunas     False  False  False  False   True  False
Klaipeda   False   True  False   True  False   True
Siauliai   False  False  False  False  False  False
Panevezys   True  False  False  False  False  False

In [38]:
dideli.isnull().sum()

U    2
V    1
W    0
X    2
Y    1
Z    1
dtype: int64

In [40]:
dideli['X'].isnull()

miestai
Vilniuas      True
Kaunas       False
Klaipeda      True
Siauliai     False
Panevezys    False
Name: X, dtype: bool

In [41]:
dideli['X'].isnull().sum()

2

In [42]:
dideli.dropna()

U     V   W     X     Y     Z
miestai                                   
Siauliai  48.0  96.0  55  41.0  54.0  98.0

In [43]:
dideli.dropna(axis=1)

W
miestai      
Vilniuas   73
Kaunas     48
Klaipeda   54
Siauliai   55
Panevezys  85

In [44]:
dideli.dropna(thresh=5)

U     V   W     X     Y     Z
miestai                                    
Kaunas     54.0  47.0  48  49.0   NaN  73.0
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   NaN  96.0  85  32.0  61.0  50.0

In [45]:
dideli.dropna(thresh=4, axis=1)

V   W     Y     Z
miestai                        
Vilniuas   55.0  73  34.0  40.0
Kaunas     47.0  48   NaN  73.0
Klaipeda    NaN  54  65.0   NaN
Siauliai   96.0  55  54.0  98.0
Panevezys  96.0  85  61.0  50.0

In [46]:
dideli.fillna('permazas')

U         V   W         X         Y         Z
miestai                                                        
Vilniuas   permazas      55.0  73  permazas      34.0      40.0
Kaunas         54.0      47.0  48      49.0  permazas      73.0
Klaipeda       68.0  permazas  54  permazas      65.0  permazas
Siauliai       48.0      96.0  55      41.0      54.0      98.0
Panevezys  permazas      96.0  85      32.0      61.0      50.0

In [47]:
dideli.fillna(0)

U     V   W     X     Y     Z
miestai                                    
Vilniuas    0.0  55.0  73   0.0  34.0  40.0
Kaunas     54.0  47.0  48  49.0   0.0  73.0
Klaipeda   68.0   0.0  54   0.0  65.0   0.0
Siauliai   48.0  96.0  55  41.0  54.0  98.0
Panevezys   0.0  96.0  85  32.0  61.0  50.0

In [49]:
dideli.fillna(value=dideli.mean())

U     V   W          X     Y      Z
miestai                                               
Vilniuas   56.666667  55.0  73  40.666667  34.0  40.00
Kaunas     54.000000  47.0  48  49.000000  53.5  73.00
Klaipeda   68.000000  73.5  54  40.666667  65.0  65.25
Siauliai   48.000000  96.0  55  41.000000  54.0  98.00
Panevezys  56.666667  96.0  85  32.000000  61.0  50.00

In [56]:
dideli['U'].fillna(value=dideli['U'].mean())

miestai
Vilniuas     56.666667
Kaunas       54.000000
Klaipeda     68.000000
Siauliai     48.000000
Panevezys    56.666667
Name: U, dtype: float64

In [61]:
top = pd.read_csv('./top50.csv', encoding='ISO-8859-1')
top.head()

Unnamed: 0                       Track.Name    Artist.Name           Genre   
0           1                         Señorita   Shawn Mendes    canadian pop  \
1           2                            China       Anuel AA  reggaeton flow   
2           3    boyfriend (with Social House)  Ariana Grande       dance pop   
3           4  Beautiful People (feat. Khalid)     Ed Sheeran             pop   
4           5      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap   

   Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.   
0               117      55            76              -6         8        75  \
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  
0      191               4             3          79  
1      302               8             9          92  
2      186              12            46          85  
3      198              12            19          86  
4      175              45             7          94

In [63]:
unique_genres = top['Genre'].unique()
unique_genres

array(['canadian pop', 'reggaeton flow', 'dance pop', 'pop', 'dfw rap',
       'trap music', 'country rap', 'electropop', 'reggaeton',
       'panamanian pop', 'canadian hip hop', 'latin', 'escape room',
       'pop house', 'australian pop', 'edm', 'atl hip hop', 'big room',
       'boy band', 'r&b en espanol', 'brostep'], dtype=object)

In [64]:
top[top['Genre']=='country rap']

Unnamed: 0             Track.Name Artist.Name        Genre   
8            9  Old Town Road - Remix   Lil Nas X  country rap  \
21          22                 Panini   Lil Nas X  country rap   

    Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness   
8                136      62            88              -6        11  \
21               154      59            70              -6        12   

    Valence.  Length.  Acousticness..  Speechiness.  Popularity  
8         64      157               5            10          87  
21        48      115              34             8          91

In [65]:
top['Genre'].nunique()

21

In [66]:
len(unique_genres)

21

In [67]:
top['Genre'].value_counts()

Genre
dance pop           8
pop                 7
latin               5
canadian hip hop    3
edm                 3
reggaeton           2
reggaeton flow      2
panamanian pop      2
canadian pop        2
electropop          2
country rap         2
dfw rap             2
brostep             2
trap music          1
escape room         1
pop house           1
australian pop      1
atl hip hop         1
big room            1
boy band            1
r&b en espanol      1
Name: count, dtype: int64

In [68]:
top['Length.'].sum()

10048

In [70]:
top['Length.'].head()

0    191
1    302
2    186
3    198
4    175
Name: Length., dtype: int64

In [74]:
def min_sec(secs):
    return f'{secs // 60}:{(secs % 60):02d}'

min_sec(133)

'2:13'

In [75]:
top['Length.'].apply(min_sec).head()

0    3:11
1    5:02
2    3:06
3    3:18
4    2:55
Name: Length., dtype: object

In [76]:
top['Length.Pretty'] = top['Length.'].apply(min_sec)

In [77]:
top.head()

Unnamed: 0                       Track.Name    Artist.Name           Genre   
0           1                         Señorita   Shawn Mendes    canadian pop  \
1           2                            China       Anuel AA  reggaeton flow   
2           3    boyfriend (with Social House)  Ariana Grande       dance pop   
3           4  Beautiful People (feat. Khalid)     Ed Sheeran             pop   
4           5      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap   

   Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.   
0               117      55            76              -6         8        75  \
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity Length.Pretty  
0      191               4             3          79          3:11  
1      302               8             9          92          5:02  
2      186              12            46          85          3:06  
3      198              12            19          86          3:18  
4      175              45             7          94          2:55

In [78]:
top['Energy'].apply(lambda arg: arg / 100).head()

0    0.55
1    0.81
2    0.80
3    0.65
4    0.65
Name: Energy, dtype: float64

In [81]:
top.columns

Index(['Track.Name', 'Artist.Name', 'Genre', 'Beats.Per.Minute', 'Energy',
       'Danceability', 'Loudness..dB..', 'Liveness', 'Valence.', 'Length.',
       'Acousticness..', 'Speechiness.', 'Popularity', 'Length.Pretty'],
      dtype='object')

In [80]:
top.drop('Unnamed: 0', axis=1, inplace=True)

In [82]:
top.index

RangeIndex(start=0, stop=50, step=1)

In [83]:
top.shape

(50, 14)

In [85]:
top.sort_values('Beats.Per.Minute', ascending=False)

Track.Name       Artist.Name   
2                       boyfriend (with Social House)     Ariana Grande  \
6                                              Ransom         Lil Tecca   
10                                           Callaita         Bad Bunny   
36                                         Otro Trago              Sech   
46                                          Te Robaré         Nicky Jam   
16                                         LA CANCIÓN          J Balvin   
13                                 Otro Trago - Remix              Sech   
19                                        Truth Hurts             Lizzo   
21                                             Panini         Lil Nas X   
37                     Antisocial (with Travis Scott)        Ed Sheeran   
4                         Goodbyes (Feat. Young Thug)       Post Malone   
31                                            7 rings     Ariana Grande   
38                                             Sucker    Jonas Brothers   
8                               Old Town Road - Remix         Lil Nas X   
43                                               Talk            Khalid   
9                                             bad guy     Billie Eilish   
24                       bad guy (with Justin Bieber)     Billie Eilish   
18                                             Lalala               Y2K   
20                                Piece Of Your Heart            MEDUZA   
25                                If I Can't Have You      Shawn Mendes   
0                                            Señorita      Shawn Mendes   
35  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
7                                   How Do You Sleep?         Sam Smith   
12                                  Someone You Loved     Lewis Capaldi   
1                                               China          Anuel AA   
48                                      Call You Mine  The Chainsmokers   
40                                        Higher Love              Kygo   
5                   I Don't Care (with Justin Bieber)        Ed Sheeran   
14           Money In The Grave (Drake ft. Rick Ross)             Drake   
47                                            Happier        Marshmello   
34                                  Never Really Over        Katy Perry   
26                                       Dance Monkey       Tones and I   
44                                         Con Altura           ROSALÍA   
33          The London (feat. J. Cole & Travis Scott)        Young Thug   
27                                           It's You         Ali Gatie   
32                                  0.958333333333333            Maluma   
11              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake   
42                                            Shallow         Lady Gaga   
39  fuck, i'm lonely (with Anne-Marie) - from “13 ...              Lauv   
49      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   
28                                          Con Calma      Daddy Yankee   
29                                      QUE PRETENDES          J Balvin   
3                     Beautiful People (feat. Khalid)        Ed Sheeran   
15                          No Guidance (feat. Drake)       Chris Brown   
22                               No Me Conoce - Remix       Jhay Cortez   
23                                    Soltera - Remix             Lunay   
17      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone   
45                                    One Thing Right        Marshmello   
41                              You Need To Calm Down      Taylor Swift   
30                                           Takeaway  The Chainsmokers   

               Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..   
2          dance pop               190      80            40              -4  \
6         trap music               180      64           

In [86]:
top.to_csv('top50utf.csv', encoding='utf-8')

In [87]:
duomenys_html = pd.read_html('https://lt.wikipedia.org/wiki/Vilniaus_miesto_savivaldyb%C4%97')
duomenys_html

[   Vilniaus miesto savivaldybė        Vilniaus miesto savivaldybė.1
 0                          NaN                                  NaN
 1                          NaN                                  NaN
 2                          NaN                                  NaN
 3                          NaN                                  NaN
 4                          NaN                                  NaN
 5                          NaN                                  NaN
 6                     Valstybė                              Lietuva
 7                    Apskritis                   Vilniaus apskritis
 8      Administracinis centras                              Vilnius
 9           Seniūnijų skaičius                                   21
 10                Įkūrimo data                              1995 m.
 11                       Meras                    Valdas Benkunskas
 12                         NaN                                  NaN
 13                   Gyventojų   

In [88]:
len(duomenys_html)

15

In [90]:
for nr, lentele in enumerate(duomenys_html):
    print(nr, lentele.shape)

0 (20, 2)
1 (7, 2)
2 (13, 5)
3 (8, 6)
4 (0, 1)
5 (21, 4)
6 (14, 3)
7 (11, 3)
8 (1, 4)
9 (16, 2)
10 (14, 2)
11 (6, 3)
12 (3, 3)
13 (22, 3)
14 (20, 3)


In [93]:
duomenys_html[5].head()

Seniūnija Plotas km²  Gyventojai  (2023 m.)   
0    Antakalnio seniūnija   77,2 km²                  43027  \
1  Fabijoniškių seniūnija   5,87 km²                  37360   
2     Grigiškių seniūnija    7,1 km²                  10685   
3   Justiniškių seniūnija   2,98 km²                  26263   
4  Karoliniškių seniūnija    4,0 km²                  24643   

  Gyventojų tankumas km²  (2023 m.)  
0                       557 žm./km²  
1                      6365 žm./km²  
2                      1505 žm./km²  
3                      8813 žm./km²  
4                      6161 žm./km²

In [94]:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
engine = create_engine('sqlite:///db/seniunijos.db')
session = sessionmaker(engine)()

In [95]:
duomenys_html[5].to_sql('ptu16valdos', con=engine, index=False)

21

In [96]:
valdos = pd.read_sql('ptu16valdos', con=engine)
valdos.head()

Seniūnija Plotas km²  Gyventojai  (2023 m.)   
0    Antakalnio seniūnija   77,2 km²                  43027  \
1  Fabijoniškių seniūnija   5,87 km²                  37360   
2     Grigiškių seniūnija    7,1 km²                  10685   
3   Justiniškių seniūnija   2,98 km²                  26263   
4  Karoliniškių seniūnija    4,0 km²                  24643   

  Gyventojų tankumas km²  (2023 m.)  
0                       557 žm./km²  
1                      6365 žm./km²  
2                      1505 žm./km²  
3                      8813 žm./km²  
4                      6161 žm./km²